export type FaqItem = { q: string; a: string };

export type ProductContent = {
  metaTitle: string;
  metaDescription: string;
  breadcrumbName: string;
  eyebrow: string;
  h1: string;
  geo: string;
  problem: string;
  agitation: string;
  solution: string;
  image: string;
  imageAlt: string;
  imageFlip?: boolean;
  coverageTitle: string;
  coverageItems: string[];
  carrierCategory: "salud" | "auto" | "hogar";
  faqTitle: string;
  faqs: FaqItem[];
  relatedTitle: string;
  relatedHrefs: string[];
  relatedLinkLabel: string;
  finalCtaTitle: string;
  finalCtaBody: string;
  serviceType: string;
};

export const productsEs: Record<string, ProductContent> = {
  obamacare: {
    metaTitle: "Seguro Médico Obamacare en Florida | Tampa Seguros",
    metaDescription:
      "Seguro médico ACA/Obamacare en Florida desde $5/mes según tus ingresos. Asesoría gratis en español para calificar e inscribirte con Tampa Seguros.",
    breadcrumbName: "Seguro Médico (Obamacare)",
    eyebrow: "Seguro médico ACA",
    h1: "Seguro Médico Obamacare en Florida: cobertura de salud desde $5/mes",
    geo: "El Seguro Médico Obamacare (Mercado de Seguros de Salud o ACA) es un programa federal que ofrece cobertura médica a residentes de Florida, con subsidios que pueden reducir la prima a $5/mes según tus ingresos. Tampa Seguros te ayuda a verificar si calificas, comparar planes entre aseguradoras como Florida Blue, Ambetter y Oscar, e inscribirte en español, sin costo por nuestra asesoría.",
    problem: "Sin seguro médico, una visita a la sala de emergencias o un diagnóstico inesperado puede costarte miles de dólares de tu bolsillo.",
    agitation: "Cada año, miles de floridanos pagan de más por no saber que califican para subsidios, o se quedan sin cobertura por perder la fecha límite de inscripción abierta.",
    solution: "Tampa Seguros revisa tu elegibilidad para subsidios, compara los planes ACA disponibles en tu condado y te inscribe en español, sin cobrarte nada adicional por el proceso.",
    image: "/images/seguro-obamacare-tampa-seguros.webp",
    imageAlt: "Madre e hija sonriendo durante una consulta médica cubierta por un seguro Obamacare de Tampa Seguros",
    coverageTitle: "Qué cubre un plan Obamacare",
    coverageItems: [
      "Consultas de médico primario",
      "Medicamentos recetados",
      "Sala de emergencias y hospitalización",
      "Cuidado preventivo, chequeos y vacunas",
      "Cobertura de maternidad",
      "Servicios de salud mental",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre Obamacare",
    faqs: [
      { q: "¿Quién califica para subsidios de Obamacare en Florida?", a: "Depende de tus ingresos familiares y el tamaño de tu hogar; muchas familias califican para primas desde $5 al mes. Un asesor puede calcularlo contigo en minutos." },
      { q: "¿Cuándo puedo inscribirme?", a: "Durante la Inscripción Abierta (normalmente del 1 de noviembre al 15 de enero) o fuera de esas fechas si calificas para un Periodo de Inscripción Especial por un evento de vida." },
      { q: "¿Necesito ser ciudadano para calificar?", a: "No necesariamente. Muchos residentes legales califican para planes del Mercado. Te ayudamos a identificar tus opciones según tu estatus." },
      { q: "¿Qué pasa si mis ingresos cambian durante el año?", a: "Debes reportar el cambio para ajustar tu subsidio; nosotros te ayudamos a hacer esa actualización sin costo." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguro-medicare/", "/seguro-short-term/", "/planes-medico-de-descuento/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "No dejes tu salud para después",
    finalCtaBody: "Un asesor revisa gratis si calificas para un plan de $5/mes y te inscribe sin complicaciones.",
    serviceType: "Seguro médico ACA / Marketplace",
  },

  medicare: {
    metaTitle: "Seguro Medicare en Florida | Tampa Seguros",
    metaDescription:
      "Elige tu plan Medicare Advantage o Medigap en Florida sin comisiones de tu bolsillo. Asesoría gratis en español con Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Medicare",
    eyebrow: "Seguro Medicare",
    h1: "Seguro Medicare en Florida: elige tu plan sin comisiones de tu bolsillo",
    geo: "Medicare es el seguro de salud federal para personas de 65 años o más y algunas personas con discapacidades, disponible en todo Florida. Tampa Seguros explica la diferencia entre Medicare Original, Medicare Advantage (Parte C) y planes Medigap, y ayuda a elegir el plan que mejor cubre tus medicamentos y médicos preferidos, en español y sin costo adicional para ti.",
    problem: "Medicare tiene múltiples partes y cientos de planes Advantage disponibles en Florida, lo que hace fácil elegir un plan que no cubre tus medicamentos o tu doctor de cabecera.",
    agitation: "Elegir el plan equivocado puede dejarte pagando copagos altos todo el año, o sin cobertura para el especialista que ya conoces y en quien confías.",
    solution: "Un asesor de Tampa Seguros compara los planes Medicare Advantage y Medigap disponibles en tu zona, revisa tu lista de medicamentos y te recomienda la opción que más te conviene, sin presión ni costo.",
    image: "/images/seguro-medicare-tampa-seguros.webp",
    imageAlt: "Pareja de adultos mayores revisando juntos las opciones de su plan Medicare con Tampa Seguros",
    coverageTitle: "Las partes de Medicare, explicadas simple",
    coverageItems: [
      "Parte A: hospitalización",
      "Parte B: consultas y médico",
      "Parte C (Advantage): todo en un plan",
      "Parte D: medicamentos recetados",
      "Medigap: complementa el Medicare Original",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre Medicare",
    faqs: [
      { q: "¿Cuándo puedo inscribirme en Medicare?", a: "Tu Periodo de Inscripción Inicial empieza 3 meses antes de cumplir 65 años. También hay una Inscripción Abierta anual del 15 de octubre al 7 de diciembre para cambiar de plan." },
      { q: "¿Cuál es la diferencia entre Medicare Advantage y Medigap?", a: "Medicare Advantage reemplaza tu Medicare Original con un plan todo en uno, mientras que Medigap complementa el Medicare Original cubriendo gastos que este no paga." },
      { q: "¿Medicare cubre medicamentos recetados?", a: "La Parte D cubre medicamentos, y muchos planes Advantage ya la incluyen. Revisamos tu lista de medicamentos para confirmar que estén cubiertos." },
      { q: "¿Tiene costo la asesoría de Tampa Seguros para Medicare?", a: "No, nuestra asesoría es gratuita; nuestra compensación viene directamente de la aseguradora, nunca de ti." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguro-medico-obamacare/", "/seguro-vision-y-dental/", "/plan-funeral/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Elige tu plan Medicare con confianza",
    finalCtaBody: "Un asesor licenciado compara tus opciones y te explica cada plan sin prisa, en español.",
    serviceType: "Seguro Medicare (Advantage y Medigap)",
  },

  vida: {
    metaTitle: "Seguro de Vida en Florida | Tampa Seguros",
    metaDescription:
      "Protege el futuro económico de tu familia con un seguro de vida en Florida. Cotiza gratis en español con Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Seguro de Vida",
    eyebrow: "Seguro de vida",
    h1: "Seguro de Vida en Florida: protege el futuro de tu familia",
    geo: "El Seguro de Vida es una póliza que entrega un beneficio económico a tus seres queridos si tú faltas, ayudando a cubrir gastos como renta, deudas o educación. Tampa Seguros ofrece opciones de vida término y vida entera para residentes de Florida, con montos de cobertura ajustados a tu presupuesto y sin necesidad de exámenes médicos extensos en muchos casos.",
    problem: "Si algo te pasara mañana, ¿tu familia podría cubrir la renta, las deudas o los estudios de tus hijos sin tu ingreso?",
    agitation: "Sin un seguro de vida, tu familia podría verse obligada a vender bienes, mudarse o endeudarse para cubrir gastos básicos en el peor momento posible.",
    solution: "Con una póliza de vida de Tampa Seguros, defines un monto de protección accesible para tu presupuesto, y tu familia recibe ese beneficio libre de impuestos cuando más lo necesita.",
    image: "/images/seguro-vida-tampa-seguros.webp",
    imageAlt: "Padre de familia abrazando a sus hijos, protegidos por un seguro de vida de Tampa Seguros",
    coverageTitle: "Opciones de seguro de vida disponibles",
    coverageItems: [
      "Vida término (10, 20 o 30 años)",
      "Vida entera con valor en efectivo",
      "Beneficio por muerte accidental",
      "Opciones sin examen médico",
      "Beneficio en vida por enfermedad terminal",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre seguro de vida",
    faqs: [
      { q: "¿Cuánta cobertura de vida necesito?", a: "Una regla común es de 10 a 15 veces tu ingreso anual, pero depende de tus deudas, dependientes y metas familiares. Un asesor puede calcularlo contigo." },
      { q: "¿Necesito un examen médico?", a: "No siempre. Existen pólizas de emisión simplificada que no requieren examen médico, aunque suelen tener montos de cobertura más limitados." },
      { q: "¿Cuál es la diferencia entre vida término y vida entera?", a: "La vida término cubre un periodo fijo (por ejemplo 20 años) a menor costo; la vida entera dura toda tu vida y acumula valor en efectivo, a un costo mayor." },
      { q: "¿Puedo cambiar mi beneficiario después?", a: "Sí, puedes actualizar tu beneficiario en cualquier momento sin costo adicional." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/plan-funeral/", "/seguro-medico-obamacare/", "/seguros-de-hogar/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Tu familia merece esa tranquilidad",
    finalCtaBody: "Cotiza tu seguro de vida hoy y descubre cuánto cuesta proteger a quienes más quieres.",
    serviceType: "Seguro de vida término y vida entera",
  },

  funeral: {
    metaTitle: "Plan Funeral en Florida | Tampa Seguros",
    metaDescription:
      "Plan funeral y de gastos finales en Florida, aprobación rápida sin examen médico. Cotiza gratis en español con Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Plan Funeral",
    eyebrow: "Plan funeral",
    h1: "Plan Funeral en Florida: evita que tu familia cargue con gastos inesperados",
    geo: "Un Plan Funeral (o seguro de gastos finales) es una póliza de bajo costo diseñada para cubrir servicios funerarios, cremación y trámites relacionados, evitando que tu familia enfrente una factura inesperada de miles de dólares. Tampa Seguros ofrece planes accesibles para adultos en Florida, con aprobación rápida y sin exámenes médicos en la mayoría de los casos.",
    problem: "Un funeral en Florida puede costar entre $7,000 y $12,000, un gasto que muchas familias no tienen guardado cuando ocurre una pérdida.",
    agitation: "Sin un plan funeral, tu familia podría tener que endeudarse o hacer una colecta urgente para poder despedirte con dignidad, justo en el momento más doloroso.",
    solution: "Con un Plan Funeral de Tampa Seguros, aseguras una cantidad fija y accesible en pagos mensuales bajos, para que tu familia reciba el dinero rápido y sin complicaciones cuando lo necesite.",
    image: "/images/plan-funeral-tampa-seguros.webp",
    imageAlt: "Familia reunida y apoyándose, representando la tranquilidad de contar con un plan funeral de Tampa Seguros",
    imageFlip: true,
    coverageTitle: "Qué cubre un plan funeral",
    coverageItems: [
      "Servicios funerarios y cremación",
      "Ataúd y preparación",
      "Traslado del cuerpo",
      "Trámites y documentos",
      "Aprobación rápida sin examen médico",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre planes funerales",
    faqs: [
      { q: "¿A qué edad puedo contratar un plan funeral?", a: "La mayoría de nuestros planes están disponibles para adultos, generalmente desde los 40 hasta los 85 años, aunque varía por aseguradora." },
      { q: "¿Necesito hacerme un examen médico?", a: "La mayoría de los planes funerales usan solo un cuestionario de salud, sin examen médico ni análisis de sangre." },
      { q: "¿Cuánto tarda en pagar el beneficio?", a: "Muchas pólizas de gastos finales pagan el beneficio en 24 a 48 horas después de aprobado el reclamo, mucho más rápido que un seguro de vida tradicional." },
      { q: "¿El costo del plan sube con el tiempo?", a: "La mayoría de los planes que ofrecemos tienen una prima fija que no aumenta con la edad, mientras mantengas tus pagos al día." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguro-de-vida/", "/seguro-medicare/", "/seguro-medico-obamacare/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Dale tranquilidad a tu familia hoy",
    finalCtaBody: "Cotiza tu plan funeral en minutos, con pagos mensuales accesibles y aprobación rápida.",
    serviceType: "Plan funeral y gastos finales",
  },

  shortTerm: {
    metaTitle: "Seguro Médico Short Term en Florida | Tampa Seguros",
    metaDescription:
      "Seguro médico temporal (Short Term) en Florida con aprobación en 24-48 horas. Cotiza gratis en español con Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Seguro Short Term",
    eyebrow: "Seguro médico temporal",
    h1: "Seguro Médico Short Term en Florida: cobertura temporal mientras decides",
    geo: "El Seguro Médico Short Term (a corto plazo) ofrece cobertura temporal de salud, generalmente de 30 días hasta 12 meses, ideal para quienes están entre empleos, esperando el periodo de inscripción de Obamacare, o recién llegados a Florida. Tampa Seguros ayuda a comparar planes short term con aprobación rápida, para que no te quedes sin protección médica en un periodo de transición.",
    problem: "Quedarte sin seguro médico, aunque sea por unas semanas, te deja completamente expuesto a facturas médicas inesperadas.",
    agitation: "Un accidente o una emergencia durante un periodo sin cobertura puede generar deudas médicas que tardan años en pagarse.",
    solution: "Un plan Short Term de Tampa Seguros te da cobertura rápida, en días, mientras esperas tu fecha de inscripción a Obamacare, cambias de empleo o resuelves tu situación laboral.",
    image: "/images/seguro-short-term-tampa-seguros.webp",
    imageAlt: "Joven profesional revisando su cobertura médica temporal Short Term con Tampa Seguros",
    imageFlip: true,
    coverageTitle: "Qué esperar de un plan Short Term",
    coverageItems: [
      "Cobertura desde 30 días hasta 12 meses",
      "Aprobación en 24-48 horas",
      "Acceso a hospitales y médicos",
      "Renovable en muchos casos",
      "Ideal para periodos de transición",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre Short Term",
    faqs: [
      { q: "¿Cuánto dura un plan Short Term?", a: "Puede durar desde 30 días hasta 12 meses, según el plan. Te ayudamos a elegir la duración que mejor se ajuste a tu situación." },
      { q: "¿Cubre condiciones preexistentes?", a: "Generalmente no; los planes short term no están obligados a cubrir condiciones preexistentes como los planes ACA. Revisamos tu caso para confirmarlo." },
      { q: "¿Es más barato que Obamacare?", a: "Suele tener una prima mensual más baja, pero también menos beneficios cubiertos. Te explicamos las diferencias para que decidas con toda la información." },
      { q: "¿Puedo tener un plan Short Term y luego cambiarme a Obamacare?", a: "Sí, muchos clientes usan Short Term como puente hasta su próxima fecha de inscripción abierta en el Mercado." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguro-medico-obamacare/", "/planes-medico-de-descuento/", "/seguro-medicare/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "No te quedes sin cobertura ni un solo día",
    finalCtaBody: "Cotiza tu plan Short Term hoy y ten protección médica en cuestión de días.",
    serviceType: "Seguro médico temporal (short term)",
  },

  descuento: {
    metaTitle: "Plan Médico de Descuento en Florida | Tampa Seguros",
    metaDescription:
      "Ahorra en consultas, medicinas y dental desde el primer mes con un plan de descuento médico en Florida. Cotiza gratis con Tampa Seguros.",
    breadcrumbName: "Plan Médico de Descuento",
    eyebrow: "Plan de descuento médico",
    h1: "Plan Médico de Descuento en Florida: ahorra en consultas y medicinas desde el primer día",
    geo: "Un Plan Médico de Descuento no es un seguro, sino una membresía que da acceso a tarifas reducidas en consultas médicas, dental, visión y medicamentos, con costos mensuales bajos y sin periodos de espera. Tampa Seguros ofrece estos planes como una opción accesible para quienes no califican para subsidios de Obamacare o necesitan ahorrar mientras consiguen un seguro completo.",
    problem: "No calificar para un subsidio de salud no significa que no necesites cuidado médico accesible para ti y tu familia.",
    agitation: "Sin ningún tipo de cobertura o membresía, pagar consultas, medicinas o cuidado dental de tu bolsillo se acumula rápido y te hace posponer cuidados que no deberías posponer.",
    solution: "Un Plan Médico de Descuento de Tampa Seguros te da acceso inmediato a tarifas reducidas en miles de proveedores en Florida, desde el primer mes y sin exámenes ni periodos de espera.",
    image: "/images/plan-descuento-medico-tampa-seguros.webp",
    imageAlt: "Persona sonriendo al recibir sus medicinas con descuento gracias a su plan médico de Tampa Seguros",
    coverageTitle: "Qué incluye un plan de descuento",
    coverageItems: [
      "Descuentos en consultas médicas",
      "Descuentos en medicamentos recetados",
      "Descuentos dentales y de visión",
      "Sin periodos de espera",
      "Activación el mismo mes",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre planes de descuento",
    faqs: [
      { q: "¿Un plan de descuento es lo mismo que un seguro?", a: "No. Un plan de descuento te da tarifas reducidas al pagar directamente; un seguro paga parte de la factura por ti. Muchas familias los combinan." },
      { q: "¿Cuánto puedo ahorrar con un plan de descuento?", a: "Los ahorros varían según el servicio, pero muchos clientes reportan descuentos de 10% a 60% en consultas, dental y medicinas." },
      { q: "¿Hay periodo de espera para usarlo?", a: "No, la mayoría de nuestros planes de descuento se activan de inmediato, incluso puedes usarlos el mismo mes que te inscribes." },
      { q: "¿Puedo tener un plan de descuento junto con Obamacare?", a: "Sí, muchos clientes usan el plan de descuento para servicios que su seguro principal no cubre completamente, como dental o visión." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguro-vision-y-dental/", "/seguro-short-term/", "/seguro-medico-obamacare/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Empieza a ahorrar en tu salud este mismo mes",
    finalCtaBody: "Cotiza tu plan de descuento médico y actívalo en minutos, sin exámenes ni esperas.",
    serviceType: "Plan médico de descuento (membresía)",
  },

  visionDental: {
    metaTitle: "Seguro de Visión y Dental en Florida | Tampa Seguros",
    metaDescription:
      "Seguro de visión y dental para toda la familia en Florida. Chequeos, limpiezas y descuentos en lentes. Cotiza gratis con Tampa Seguros.",
    breadcrumbName: "Visión y Dental",
    eyebrow: "Visión y dental",
    h1: "Seguro de Visión y Dental en Florida para toda la familia",
    geo: "El Seguro de Visión y Dental cubre exámenes de la vista, lentes, limpiezas dentales y procedimientos dentales básicos que la mayoría de los planes médicos generales no incluyen. Tampa Seguros ofrece opciones independientes o combinadas de visión y dental para familias en Florida, con primas accesibles y redes amplias de proveedores, para que el cuidado preventivo no se quede pendiente por costo.",
    problem: "La mayoría de los seguros médicos no cubren cuidado dental ni de la vista, dejando estos gastos completamente a tu cargo.",
    agitation: "Posponer una limpieza dental o un examen de la vista por costo casi siempre termina costando más caro cuando el problema se vuelve una urgencia.",
    solution: "Con un plan de Visión y Dental de Tampa Seguros, cubres chequeos preventivos, limpiezas y una parte de procedimientos mayores, por una prima mensual accesible para toda la familia.",
    image: "/images/seguro-vision-dental-tampa-seguros.webp",
    imageAlt: "Niña sonriendo en el dentista, cubierta por el seguro de visión y dental de Tampa Seguros",
    coverageTitle: "Qué cubre visión y dental",
    coverageItems: [
      "Exámenes de la vista anuales",
      "Lentes y armazones con descuento",
      "Limpiezas dentales cada 6 meses",
      "Rellenos y extracciones básicas",
      "Planes para toda la familia",
    ],
    carrierCategory: "salud",
    faqTitle: "Preguntas frecuentes sobre visión y dental",
    faqs: [
      { q: "¿Puedo tener visión y dental por separado?", a: "Sí, ofrecemos planes independientes de visión y dental, o combinados en una sola prima mensual, según lo que necesite tu familia." },
      { q: "¿Cubre ortodoncia o brackets?", a: "Algunos planes incluyen un beneficio parcial para ortodoncia en menores. Revisamos las opciones disponibles según tu presupuesto." },
      { q: "¿Tiene periodo de espera?", a: "Los chequeos preventivos suelen estar disponibles desde el primer mes; algunos procedimientos mayores pueden tener un periodo de espera corto." },
      { q: "¿Puedo agregarlo a mi seguro médico actual?", a: "Sí, la mayoría de nuestros clientes lo contratan como complemento a su seguro médico principal." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/planes-medico-de-descuento/", "/seguro-medico-obamacare/", "/seguro-medicare/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "El cuidado preventivo no debería esperar",
    finalCtaBody: "Cotiza tu plan de visión y dental para toda la familia en minutos.",
    serviceType: "Seguro de visión y dental",
  },

  auto: {
    metaTitle: "Seguro de Auto en Florida | Tampa Seguros",
    metaDescription:
      "Cotiza tu seguro de auto en Florida y cumple con la ley al mejor precio. Comparamos Progressive, GEICO y más. Asesoría gratis en español.",
    breadcrumbName: "Seguro de Auto",
    eyebrow: "Seguro de auto",
    h1: "Seguro de Auto en Florida: la cobertura que exige la ley, al mejor precio",
    geo: "El Seguro de Auto es obligatorio en Florida bajo la ley de No-Fault, que exige un mínimo de cobertura PIP (Protección por Lesiones Personales) y PDL (Daños a la Propiedad). Tampa Seguros compara cotizaciones entre aseguradoras como Progressive, GEICO y Allstate para encontrar la prima más baja posible, con la cobertura legal y las opciones adicionales que tu vehículo necesita.",
    problem: "Manejar sin la cobertura mínima que exige Florida te expone a multas, suspensión de licencia y a pagar de tu bolsillo si ocurre un accidente.",
    agitation: "Muchos conductores pagan más de lo necesario por no comparar cotizaciones entre aseguradoras, o se quedan con cobertura insuficiente después de un choque.",
    solution: "Tampa Seguros compara tu cotización entre varias aseguradoras licenciadas en Florida en minutos, para que cumplas con la ley y no pagues de más por tu póliza de auto.",
    image: "/images/seguro-auto-tampa-seguros.webp",
    imageAlt: "Hombre entregando las llaves de su auto, ya protegido con un seguro de auto de Tampa Seguros",
    coverageTitle: "Qué incluye tu póliza de auto",
    coverageItems: [
      "PIP: Protección por Lesiones Personales",
      "PDL: Daños a la Propiedad",
      "Cobertura de colisión (opcional)",
      "Cobertura amplia / comprensiva (opcional)",
      "Asistencia en el camino",
    ],
    carrierCategory: "auto",
    faqTitle: "Preguntas frecuentes sobre seguro de auto",
    faqs: [
      { q: "¿Cuál es el seguro de auto mínimo obligatorio en Florida?", a: "Florida exige al menos $10,000 en PIP y $10,000 en PDL. Un asesor puede confirmar si necesitas cobertura adicional según tu vehículo." },
      { q: "¿Puedo bajar el precio de mi póliza de auto?", a: "Sí, comparar entre aseguradoras, mantener un buen historial de manejo y combinar pólizas (como auto y hogar) suele reducir el costo." },
      { q: "¿Necesito seguro de auto si no tengo licencia de Florida?", a: "Las reglas varían según tu situación; te ayudamos a confirmar qué aplica según tu documentación y tiempo de residencia." },
      { q: "¿Qué pasa si tengo un accidente sin cobertura amplia?", a: "Sin cobertura de colisión, tendrías que pagar de tu bolsillo la reparación de tu propio vehículo. Podemos ayudarte a decidir si te conviene agregarla." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguros-de-hogar/", "/seguro-medico-obamacare/", "/seguro-de-vida/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Compara y ahorra en tu seguro de auto",
    finalCtaBody: "Cotiza en minutos entre varias aseguradoras y maneja tranquilo, cumpliendo la ley.",
    serviceType: "Seguro de auto",
  },

  hogar: {
    metaTitle: "Seguro de Hogar en Florida | Tampa Seguros",
    metaDescription:
      "Seguro de hogar e inquilinos en Florida con cobertura de viento y huracán. Cotiza gratis en español con Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Seguro de Hogar",
    eyebrow: "Seguro de hogar",
    h1: "Seguro de Hogar en Florida: protege tu casa o tu alquiler ante huracanes y más",
    geo: "El Seguro de Hogar protege tu vivienda y tus pertenencias contra huracanes, incendios, robos y otros daños, mientras que el seguro de inquilinos protege tus pertenencias si rentas. Tampa Seguros compara opciones entre aseguradoras especializadas en el clima de Florida, incluyendo cobertura de viento e inundación, para que tu hogar esté protegido durante la temporada de huracanes y todo el año.",
    problem: "Un huracán, una tubería rota o un robo pueden destruir en minutos lo que te tomó años construir en tu hogar.",
    agitation: "En Florida, muchas pólizas estándar no cubren viento o inundación automáticamente, dejando a los propietarios con gastos de reparación de decenas de miles de dólares tras una tormenta.",
    solution: "Tampa Seguros compara pólizas de hogar e inquilinos entre aseguradoras que entienden el riesgo climático de Florida, y te asegura que tengas la cobertura de viento e inundación que realmente necesitas.",
    image: "/images/seguro-hogar-inquilinos-tampa-seguros.webp",
    imageAlt: "Familia frente a su casa en Florida, protegida por un seguro de hogar de Tampa Seguros",
    coverageTitle: "Qué cubre tu seguro de hogar",
    coverageItems: [
      "Daños por viento y huracán",
      "Cobertura de inundación (opcional/separada)",
      "Incendio y robo",
      "Responsabilidad civil en tu propiedad",
      "Seguro de inquilinos para pertenencias",
    ],
    carrierCategory: "hogar",
    faqTitle: "Preguntas frecuentes sobre seguro de hogar",
    faqs: [
      { q: "¿El seguro de hogar cubre huracanes?", a: "La mayoría cubre daños por viento, pero la inundación suele requerir una póliza separada. Te ayudamos a confirmar qué necesitas según tu zona." },
      { q: "¿Necesito seguro si rento en vez de ser dueño?", a: "Sí, un seguro de inquilinos protege tus pertenencias y te da responsabilidad civil, y suele costar muy poco al mes." },
      { q: "¿Qué es la cobertura de inundación y por qué es separada?", a: "La mayoría de las pólizas de hogar excluyen inundación; se contrata aparte, muchas veces a través del programa federal NFIP o aseguradoras privadas." },
      { q: "¿Puedo combinar mi seguro de hogar y de auto?", a: "Sí, combinar pólizas con la misma aseguradora casi siempre reduce el costo total. Podemos cotizarte ambas juntas." },
    ],
    relatedTitle: "Otros seguros que te pueden interesar",
    relatedHrefs: ["/seguros-de-autos/", "/seguro-de-vida/", "/seguro-medico-obamacare/"],
    relatedLinkLabel: "Ver detalles",
    finalCtaTitle: "Prepara tu hogar antes de la próxima tormenta",
    finalCtaBody: "Cotiza tu seguro de hogar o inquilinos y asegúrate de tener la cobertura correcta.",
    serviceType: "Seguro de hogar e inquilinos",
  },
};

export const productsEn: Record<string, ProductContent> = {
  obamacare: {
    metaTitle: "ACA / Obamacare Health Insurance in Florida | Tampa Seguros",
    metaDescription:
      "ACA/Obamacare health insurance in Florida from $5/month based on income. Free bilingual guidance to qualify and enroll with Tampa Seguros.",
    breadcrumbName: "Health Insurance (ACA)",
    eyebrow: "ACA health insurance",
    h1: "ACA / Obamacare Health Insurance in Florida: coverage from $5/month",
    geo: "ACA (Obamacare) health insurance is a federal program offering medical coverage to Florida residents, with subsidies that can lower your premium to $5/month depending on income. Tampa Seguros checks whether you qualify, compares plans across carriers like Florida Blue, Ambetter and Oscar, and enrolls you in Spanish or English, at no cost for our guidance.",
    problem: "Without health insurance, one ER visit or an unexpected diagnosis can cost you thousands of dollars out of pocket.",
    agitation: "Every year, thousands of Floridians overpay because they don't know they qualify for subsidies, or lose coverage by missing the open enrollment deadline.",
    solution: "Tampa Seguros checks your subsidy eligibility, compares the ACA plans available in your county, and enrolls you at no extra cost for the process.",
    image: "/images/seguro-obamacare-tampa-seguros.webp",
    imageAlt: "Mother and daughter smiling during a doctor visit covered by an Obamacare plan from Tampa Seguros",
    coverageTitle: "What an ACA plan covers",
    coverageItems: [
      "Primary care visits",
      "Prescription drugs",
      "ER visits and hospitalization",
      "Preventive care, checkups and vaccines",
      "Maternity coverage",
      "Mental health services",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about ACA/Obamacare",
    faqs: [
      { q: "Who qualifies for ACA subsidies in Florida?", a: "It depends on your household income and family size; many families qualify for premiums starting at $5 a month. An advisor can calculate this with you in minutes." },
      { q: "When can I enroll?", a: "During Open Enrollment (typically November 1 to January 15), or outside that window if you qualify for a Special Enrollment Period due to a life event." },
      { q: "Do I need to be a citizen to qualify?", a: "Not necessarily. Many legal residents qualify for Marketplace plans. We help you identify your options based on your status." },
      { q: "What if my income changes during the year?", a: "You should report the change to adjust your subsidy; we help you make that update at no cost." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/medicare-insurance/", "/en/short-term-health-insurance/", "/en/medical-discount-plans/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Don't put your health on hold",
    finalCtaBody: "An advisor checks for free if you qualify for a $5/month plan and enrolls you with no hassle.",
    serviceType: "ACA / Marketplace health insurance",
  },

  medicare: {
    metaTitle: "Medicare Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Choose your Medicare Advantage or Medigap plan in Florida at no cost to you. Free bilingual guidance with Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Medicare",
    eyebrow: "Medicare insurance",
    h1: "Medicare Insurance in Florida: choose your plan at no cost to you",
    geo: "Medicare is the federal health insurance program for people 65 and older, and some people with disabilities, available across Florida. Tampa Seguros explains the difference between Original Medicare, Medicare Advantage (Part C) and Medigap plans, and helps you choose the plan that best covers your medications and preferred doctors, at no extra cost to you.",
    problem: "Medicare has multiple parts and hundreds of Advantage plans available in Florida, making it easy to pick a plan that doesn't cover your medications or your primary doctor.",
    agitation: "Choosing the wrong plan can leave you paying high copays all year, or without coverage for the specialist you already know and trust.",
    solution: "A Tampa Seguros advisor compares the Medicare Advantage and Medigap plans available in your area, checks your medication list, and recommends the option that fits you best, with no pressure and no cost.",
    image: "/images/seguro-medicare-tampa-seguros.webp",
    imageAlt: "Senior couple reviewing their Medicare plan options together with Tampa Seguros",
    coverageTitle: "The parts of Medicare, explained simply",
    coverageItems: [
      "Part A: hospital coverage",
      "Part B: doctor visits",
      "Part C (Advantage): all-in-one plan",
      "Part D: prescription drugs",
      "Medigap: supplements Original Medicare",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about Medicare",
    faqs: [
      { q: "When can I enroll in Medicare?", a: "Your Initial Enrollment Period starts 3 months before you turn 65. There's also an annual Open Enrollment from October 15 to December 7 to change plans." },
      { q: "What's the difference between Medicare Advantage and Medigap?", a: "Medicare Advantage replaces Original Medicare with an all-in-one plan, while Medigap supplements Original Medicare by covering costs it doesn't pay." },
      { q: "Does Medicare cover prescription drugs?", a: "Part D covers medications, and many Advantage plans already include it. We review your medication list to confirm coverage." },
      { q: "Does Tampa Seguros charge for Medicare guidance?", a: "No, our guidance is free; our compensation comes directly from the carrier, never from you." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/aca-obamacare-health-insurance/", "/en/vision-and-dental-insurance/", "/en/funeral-plan/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Choose your Medicare plan with confidence",
    finalCtaBody: "A licensed advisor compares your options and explains every plan clearly, with no rush.",
    serviceType: "Medicare insurance (Advantage and Medigap)",
  },

  vida: {
    metaTitle: "Life Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Protect your family's financial future with life insurance in Florida. Get a free bilingual quote with Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Life Insurance",
    eyebrow: "Life insurance",
    h1: "Life Insurance in Florida: protect your family's future",
    geo: "Life Insurance is a policy that pays a financial benefit to your loved ones if you pass away, helping cover costs like rent, debt or education. Tampa Seguros offers term and whole life options for Florida residents, with coverage amounts fitted to your budget and, in many cases, no extensive medical exam required.",
    problem: "If something happened to you tomorrow, could your family cover rent, debt or your kids' education without your income?",
    agitation: "Without life insurance, your family could be forced to sell assets, move, or take on debt to cover basic expenses at the worst possible time.",
    solution: "With a Tampa Seguros life policy, you set a protection amount that fits your budget, and your family receives that benefit tax-free exactly when they need it most.",
    image: "/images/seguro-vida-tampa-seguros.webp",
    imageAlt: "Father hugging his children, protected by a life insurance policy from Tampa Seguros",
    coverageTitle: "Life insurance options available",
    coverageItems: [
      "Term life (10, 20 or 30 years)",
      "Whole life with cash value",
      "Accidental death benefit",
      "No medical exam options",
      "Living benefit for terminal illness",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about life insurance",
    faqs: [
      { q: "How much life coverage do I need?", a: "A common rule is 10 to 15 times your annual income, but it depends on your debts, dependents and family goals. An advisor can calculate this with you." },
      { q: "Do I need a medical exam?", a: "Not always. Simplified-issue policies exist that don't require a medical exam, though they usually offer lower coverage amounts." },
      { q: "What's the difference between term and whole life?", a: "Term life covers a fixed period (like 20 years) at a lower cost; whole life lasts your entire life and builds cash value, at a higher cost." },
      { q: "Can I change my beneficiary later?", a: "Yes, you can update your beneficiary at any time at no extra cost." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/funeral-plan/", "/en/aca-obamacare-health-insurance/", "/en/home-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Your family deserves that peace of mind",
    finalCtaBody: "Get a life insurance quote today and see how affordable protecting your loved ones can be.",
    serviceType: "Term and whole life insurance",
  },

  funeral: {
    metaTitle: "Funeral Plan in Florida | Tampa Seguros",
    metaDescription:
      "Funeral and final expense plans in Florida, fast approval with no medical exam. Get a free bilingual quote with Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Funeral Plan",
    eyebrow: "Funeral plan",
    h1: "Funeral Plan in Florida: spare your family unexpected expenses",
    geo: "A Funeral Plan (or final expense insurance) is a low-cost policy designed to cover funeral services, cremation and related arrangements, so your family doesn't face an unexpected bill of thousands of dollars. Tampa Seguros offers accessible plans for adults in Florida, with fast approval and no medical exam in most cases.",
    problem: "A funeral in Florida can cost between $7,000 and $12,000, an expense most families haven't set aside when a loss occurs.",
    agitation: "Without a funeral plan, your family may need to take on debt or scramble to raise funds just to say goodbye with dignity, at the most painful moment possible.",
    solution: "With a Tampa Seguros Funeral Plan, you lock in a fixed, affordable amount through low monthly payments, so your family receives the money quickly and without complications when they need it.",
    image: "/images/plan-funeral-tampa-seguros.webp",
    imageAlt: "Family gathered and supporting each other, reflecting the peace of mind of a Tampa Seguros funeral plan",
    imageFlip: true,
    coverageTitle: "What a funeral plan covers",
    coverageItems: [
      "Funeral services and cremation",
      "Casket and preparation",
      "Transport of remains",
      "Paperwork and arrangements",
      "Fast approval, no medical exam",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about funeral plans",
    faqs: [
      { q: "At what age can I get a funeral plan?", a: "Most of our plans are available for adults, generally from age 40 to 85, though this varies by carrier." },
      { q: "Do I need a medical exam?", a: "Most funeral plans use only a health questionnaire, with no medical exam or blood work." },
      { q: "How fast is the benefit paid?", a: "Many final expense policies pay the benefit within 24 to 48 hours after an approved claim, much faster than traditional life insurance." },
      { q: "Does the plan's cost increase over time?", a: "Most of the plans we offer have a fixed premium that doesn't increase with age, as long as your payments stay current." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/life-insurance/", "/en/medicare-insurance/", "/en/aca-obamacare-health-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Give your family that peace of mind today",
    finalCtaBody: "Get your funeral plan quote in minutes, with affordable monthly payments and fast approval.",
    serviceType: "Funeral and final expense plan",
  },

  shortTerm: {
    metaTitle: "Short Term Health Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Short term health insurance in Florida with 24-48 hour approval. Get a free bilingual quote with Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Short Term Health",
    eyebrow: "Short term health insurance",
    h1: "Short Term Health Insurance in Florida: coverage while you decide",
    geo: "Short Term health insurance offers temporary medical coverage, typically from 30 days up to 12 months, ideal for people between jobs, waiting for ACA open enrollment, or newly arrived in Florida. Tampa Seguros helps compare short term plans with fast approval, so you're never left without medical protection during a transition period.",
    problem: "Going without health insurance, even for a few weeks, leaves you fully exposed to unexpected medical bills.",
    agitation: "An accident or emergency during a coverage gap can create medical debt that takes years to pay off.",
    solution: "A Tampa Seguros Short Term plan gives you fast coverage, in days, while you wait for your ACA enrollment window or sort out a job change.",
    image: "/images/seguro-short-term-tampa-seguros.webp",
    imageAlt: "Young professional reviewing his temporary short term health coverage with Tampa Seguros",
    imageFlip: true,
    coverageTitle: "What to expect from a Short Term plan",
    coverageItems: [
      "Coverage from 30 days up to 12 months",
      "Approval in 24-48 hours",
      "Access to hospitals and doctors",
      "Renewable in many cases",
      "Ideal for transition periods",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about Short Term plans",
    faqs: [
      { q: "How long does a Short Term plan last?", a: "It can last from 30 days up to 12 months, depending on the plan. We help you choose the duration that fits your situation." },
      { q: "Does it cover pre-existing conditions?", a: "Generally no; short term plans aren't required to cover pre-existing conditions like ACA plans. We review your case to confirm." },
      { q: "Is it cheaper than ACA/Obamacare?", a: "It usually has a lower monthly premium, but fewer covered benefits. We explain the differences so you can decide with full information." },
      { q: "Can I get a Short Term plan and later switch to ACA?", a: "Yes, many clients use Short Term as a bridge until their next Marketplace open enrollment window." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/aca-obamacare-health-insurance/", "/en/medical-discount-plans/", "/en/medicare-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Don't go a single day without coverage",
    finalCtaBody: "Get your Short Term plan quote today and have medical protection within days.",
    serviceType: "Short term health insurance",
  },

  descuento: {
    metaTitle: "Medical Discount Plans in Florida | Tampa Seguros",
    metaDescription:
      "Save on visits, medicine and dental from day one with a medical discount plan in Florida. Get a free bilingual quote with Tampa Seguros.",
    breadcrumbName: "Medical Discount Plans",
    eyebrow: "Medical discount plan",
    h1: "Medical Discount Plans in Florida: save on visits and medicine from day one",
    geo: "A Medical Discount Plan is not insurance, but a membership giving access to reduced rates on doctor visits, dental, vision and medications, with low monthly costs and no waiting periods. Tampa Seguros offers these plans as an accessible option for people who don't qualify for ACA subsidies or need to save while they secure full coverage.",
    problem: "Not qualifying for a health subsidy doesn't mean you and your family don't need affordable medical care.",
    agitation: "Without any kind of coverage or membership, paying for visits, medicine or dental care out of pocket adds up fast and makes you delay care you shouldn't delay.",
    solution: "A Tampa Seguros Medical Discount Plan gives you immediate access to reduced rates at thousands of providers across Florida, starting the first month with no exams or waiting periods.",
    image: "/images/plan-descuento-medico-tampa-seguros.webp",
    imageAlt: "Person smiling while picking up discounted medication through a Tampa Seguros medical discount plan",
    coverageTitle: "What a discount plan includes",
    coverageItems: [
      "Discounts on doctor visits",
      "Discounts on prescription drugs",
      "Dental and vision discounts",
      "No waiting periods",
      "Same-month activation",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about discount plans",
    faqs: [
      { q: "Is a discount plan the same as insurance?", a: "No. A discount plan gives you reduced rates when you pay directly; insurance pays part of the bill for you. Many families combine both." },
      { q: "How much can I save with a discount plan?", a: "Savings vary by service, but many clients report discounts of 10% to 60% on visits, dental and medicine." },
      { q: "Is there a waiting period to use it?", a: "No, most of our discount plans activate immediately, and you can use them the same month you enroll." },
      { q: "Can I have a discount plan along with ACA coverage?", a: "Yes, many clients use a discount plan for services their main insurance doesn't fully cover, like dental or vision." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/vision-and-dental-insurance/", "/en/short-term-health-insurance/", "/en/aca-obamacare-health-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Start saving on your health this month",
    finalCtaBody: "Get your medical discount plan quote and activate it in minutes, no exams or waiting.",
    serviceType: "Medical discount plan (membership)",
  },

  visionDental: {
    metaTitle: "Vision and Dental Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Vision and dental insurance for the whole family in Florida. Checkups, cleanings and discounted lenses. Get a free bilingual quote today.",
    breadcrumbName: "Vision & Dental",
    eyebrow: "Vision and dental",
    h1: "Vision and Dental Insurance in Florida for the whole family",
    geo: "Vision and Dental insurance covers eye exams, lenses, dental cleanings and basic dental procedures that most general health plans don't include. Tampa Seguros offers standalone or combined vision and dental options for Florida families, with affordable premiums and wide provider networks, so preventive care never gets postponed over cost.",
    problem: "Most health plans don't cover dental or vision care, leaving those costs entirely on you.",
    agitation: "Postponing a dental cleaning or an eye exam over cost almost always ends up costing more once the problem becomes an emergency.",
    solution: "With a Tampa Seguros Vision and Dental plan, you cover preventive checkups, cleanings and part of major procedures, for an affordable monthly premium for the whole family.",
    image: "/images/seguro-vision-dental-tampa-seguros.webp",
    imageAlt: "Girl smiling at the dentist, covered by Tampa Seguros vision and dental insurance",
    coverageTitle: "What vision and dental covers",
    coverageItems: [
      "Annual eye exams",
      "Discounted lenses and frames",
      "Dental cleanings every 6 months",
      "Basic fillings and extractions",
      "Plans for the whole family",
    ],
    carrierCategory: "salud",
    faqTitle: "Frequently asked questions about vision and dental",
    faqs: [
      { q: "Can I get vision and dental separately?", a: "Yes, we offer standalone vision and dental plans, or combined into a single monthly premium, depending on what your family needs." },
      { q: "Does it cover orthodontics or braces?", a: "Some plans include a partial benefit for orthodontics for minors. We review the options available for your budget." },
      { q: "Is there a waiting period?", a: "Preventive checkups are usually available from month one; some major procedures may have a short waiting period." },
      { q: "Can I add it to my current health insurance?", a: "Yes, most of our clients get it as a complement to their main health plan." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/medical-discount-plans/", "/en/aca-obamacare-health-insurance/", "/en/medicare-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Preventive care shouldn't wait",
    finalCtaBody: "Get your vision and dental plan quote for the whole family in minutes.",
    serviceType: "Vision and dental insurance",
  },

  auto: {
    metaTitle: "Auto Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Get a Florida auto insurance quote and meet the legal requirement at the best price. We compare Progressive, GEICO and more. Free guidance.",
    breadcrumbName: "Auto Insurance",
    eyebrow: "Auto insurance",
    h1: "Auto Insurance in Florida: the coverage the law requires, at the best price",
    geo: "Auto Insurance is mandatory in Florida under the No-Fault law, requiring minimum PIP (Personal Injury Protection) and PDL (Property Damage Liability) coverage. Tampa Seguros compares quotes across carriers like Progressive, GEICO and Allstate to find the lowest possible premium, with the legal coverage and additional options your vehicle needs.",
    problem: "Driving without Florida's minimum required coverage exposes you to fines, license suspension, and out-of-pocket costs if an accident happens.",
    agitation: "Many drivers overpay by not comparing quotes across carriers, or end up underinsured after a crash.",
    solution: "Tampa Seguros compares your quote across several Florida-licensed carriers in minutes, so you meet the law and don't overpay for your auto policy.",
    image: "/images/seguro-auto-tampa-seguros.webp",
    imageAlt: "Man handing over his car keys, already protected with auto insurance from Tampa Seguros",
    coverageTitle: "What your auto policy includes",
    coverageItems: [
      "PIP: Personal Injury Protection",
      "PDL: Property Damage Liability",
      "Collision coverage (optional)",
      "Comprehensive coverage (optional)",
      "Roadside assistance",
    ],
    carrierCategory: "auto",
    faqTitle: "Frequently asked questions about auto insurance",
    faqs: [
      { q: "What's the minimum required auto insurance in Florida?", a: "Florida requires at least $10,000 in PIP and $10,000 in PDL. An advisor can confirm if you need additional coverage for your vehicle." },
      { q: "Can I lower the price of my auto policy?", a: "Yes, comparing carriers, keeping a good driving record, and bundling policies (like auto and home) usually reduces the cost." },
      { q: "Do I need auto insurance if I don't have a Florida license?", a: "Rules vary by situation; we help confirm what applies based on your documentation and time in the state." },
      { q: "What happens if I have an accident without comprehensive coverage?", a: "Without collision coverage, you'd pay out of pocket to repair your own vehicle. We can help you decide if it's worth adding." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/home-insurance/", "/en/aca-obamacare-health-insurance/", "/en/life-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Compare and save on your auto insurance",
    finalCtaBody: "Get a quote in minutes across several carriers and drive with peace of mind, legally covered.",
    serviceType: "Auto insurance",
  },

  hogar: {
    metaTitle: "Home Insurance in Florida | Tampa Seguros",
    metaDescription:
      "Home and renters insurance in Florida with wind and hurricane coverage. Get a free bilingual quote with Tampa Seguros (Lic. L099087).",
    breadcrumbName: "Home Insurance",
    eyebrow: "Home insurance",
    h1: "Home Insurance in Florida: protect your house or rental from hurricanes and more",
    geo: "Home Insurance protects your house and belongings against hurricanes, fire, theft and other damage, while renters insurance protects your belongings if you rent. Tampa Seguros compares options across carriers that specialize in Florida's weather risk, including wind and flood coverage, so your home is protected during hurricane season and year-round.",
    problem: "A hurricane, a burst pipe or a break-in can destroy in minutes what took you years to build in your home.",
    agitation: "In Florida, many standard policies don't automatically cover wind or flood, leaving homeowners with tens of thousands of dollars in repair costs after a storm.",
    solution: "Tampa Seguros compares home and renters policies across carriers that understand Florida's climate risk, making sure you have the wind and flood coverage you actually need.",
    image: "/images/seguro-hogar-inquilinos-tampa-seguros.webp",
    imageAlt: "Family in front of their Florida home, protected by home insurance from Tampa Seguros",
    coverageTitle: "What your home insurance covers",
    coverageItems: [
      "Wind and hurricane damage",
      "Flood coverage (optional/separate)",
      "Fire and theft",
      "Personal liability on your property",
      "Renters insurance for belongings",
    ],
    carrierCategory: "hogar",
    faqTitle: "Frequently asked questions about home insurance",
    faqs: [
      { q: "Does home insurance cover hurricanes?", a: "Most policies cover wind damage, but flooding usually requires a separate policy. We help confirm what you need based on your area." },
      { q: "Do I need insurance if I rent instead of own?", a: "Yes, renters insurance protects your belongings and gives you liability coverage, and it usually costs very little per month." },
      { q: "What is flood coverage and why is it separate?", a: "Most home policies exclude flooding; it's purchased separately, often through the federal NFIP program or private carriers." },
      { q: "Can I bundle my home and auto insurance?", a: "Yes, bundling policies with the same carrier almost always reduces the total cost. We can quote both together." },
    ],
    relatedTitle: "Other insurance you may need",
    relatedHrefs: ["/en/auto-insurance/", "/en/life-insurance/", "/en/aca-obamacare-health-insurance/"],
    relatedLinkLabel: "See details",
    finalCtaTitle: "Prepare your home before the next storm",
    finalCtaBody: "Get your home or renters insurance quote and make sure you have the right coverage.",
    serviceType: "Home and renters insurance",
  },
};
